<?php
//Custom Layouts
$layouts = array(
		'footer_16' => array(
				'name' => 'Footer Informed',
				'template' => '[vc_row full_width=\"stretch_row\" row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1493996856635{background-color: #2e2c2c !important;}\" el_class=\"footer-row\"][vc_column icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" padding=\"none\"][vc_row_inner][vc_column_inner icons_position=\"left\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1493974128492{margin-bottom: -2.3rem !important;}\"][/vc_column_inner][vc_column_inner width=\"1/6\" icons_position=\"left\"][vc_wp_custommenu nav_menu=\"42\" title=\"Golf\"][vc_empty_space height=\"\" hide_on_mobile=\"\"][/vc_column_inner][vc_column_inner width=\"1/6\" icons_position=\"left\"][vc_wp_custommenu nav_menu=\"43\" title=\"Links\"][vc_empty_space height=\"\" hide_on_mobile=\"\"][/vc_column_inner][vc_column_inner width=\"1/6\" icons_position=\"left\"][vc_wp_custommenu nav_menu=\"44\" title=\"Events\"][vc_empty_space height=\"\" hide_on_mobile=\"\"][/vc_column_inner][vc_column_inner width=\"5/12\" column_align=\"right\" icons_position=\"right\" offset=\"vc_col-lg-offset-1 vc_col-md-offset-1 vc_col-sm-offset-1\" css=\".vc_custom_1493974198228{padding-left: 2rem !important;}\"][vc_empty_space height=\"\" alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1493974150572{margin-bottom: -0.5rem !important;}\"][vc_column_text]
<h5>Sign Up to Receive Our Newsletter</h5>
[/vc_column_text][vc_empty_space height=\"\" alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1493974178201{margin-bottom: -0.8rem !important;}\"][vc_wp_text][mc4wp_form id=\"207\"][/vc_wp_text][vc_empty_space height=\"\" alter_height=\"small\" hide_on_mobile=\"\"][/vc_column_inner][vc_column_inner icons_position=\"left\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1493974397984{margin-top: -0.7rem !important;border-top-width: 1px !important;border-top-color: rgba(255,255,255,0.2) !important;border-top-style: solid !important;}\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row][vc_row full_width=\"stretch_row\" scheme=\"dark\" row_delimiter=\"\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1493997178323{background-color: #2e2c2c !important;}\" el_class=\"footer-row\"][vc_column column_align=\"center\" icons_position=\"left\" css=\".vc_custom_1493975176923{margin-top: -3.7rem !important;}\"][trx_sc_content size=\"1_1\" float=\"center\" number_position=\"br\" title_style=\"default\" padding=\"none\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner el_class=\"textalignleft\" width=\"1/2\" icons_position=\"left\"][vc_wp_text]<a href=\"https://themeforest.net/user/ancorathemes/portfolio\" target=\"_blank\" rel=\"noopener noreferrer\">AncoraThemes</a> &copy; {Y}. All rights reserved.[/vc_wp_text][/vc_column_inner][vc_column_inner width=\"1/2\" column_align=\"right\" icons_position=\"right\"][trx_sc_socials align=\"right\" icons=\"%5B%7B%22link%22%3A%22https%3A%2F%2Ftwitter.com%2Fancora_themes%22%2C%22icon%22%3A%22icon-twitter%22%7D%2C%7B%22link%22%3A%22https%3A%2F%2Fwww.instagram.com%2Fancora_themes%2F%22%2C%22icon%22%3A%22icon-instagramm%22%7D%2C%7B%22link%22%3A%22https%3A%2F%2Fwww.facebook.com%2FAncoraThemes%2F%22%2C%22icon%22%3A%22icon-facebook%22%7D%5D\" title_style=\"default\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][vc_column icons_position=\"left\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1493983856886{margin-bottom: -0.6rem !important;}\"][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'footer'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1493996856635{background-color: #2e2c2c !important;}.vc_custom_1493997178323{background-color: #2e2c2c !important;}.vc_custom_1493974198228{padding-left: 2rem !important;}.vc_custom_1493974128492{margin-bottom: -2.3rem !important;}.vc_custom_1493974150572{margin-bottom: -0.5rem !important;}.vc_custom_1493974178201{margin-bottom: -0.8rem !important;}.vc_custom_1493974397984{margin-top: -0.7rem !important;border-top-width: 1px !important;border-top-color: rgba(255,255,255,0.2) !important;border-top-style: solid !important;}.vc_custom_1493975176923{margin-top: -3.7rem !important;}.vc_custom_1493983856886{margin-bottom: -0.6rem !important;}'
						)
				),
		'header_26' => array(
				'name' => 'Header Fullwidth',
				'template' => '<p>[vc_row equal_height=\"yes\" content_placement=\"middle\" row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1493994341441{padding-top: 1.25em !important;padding-right: 2.3em !important;padding-bottom: 1.25em !important;padding-left: 2.7em !important;}\" el_class=\"ipad-row\"][vc_column width=\"1/4\" column_align=\"left\" icons_position=\"left\" column_type=\"center\" css=\".vc_custom_1493900457245{margin-top: -7px !important;}\"][trx_sc_layouts_logo][/vc_column][vc_column width=\"1/2\" column_align=\"center\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" hover=\"slide_line\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column][vc_column width=\"1/4\" column_align=\"right\" icons_position=\"left\" offset=\"vc_hidden-md vc_hidden-sm vc_hidden-xs\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"icon-phone-2\" text2=\"0 (800) 123-456\" link=\"tel:0800123456\"][trx_sc_button type=\"default\" size=\"small\" color_style=\"link2\" icon_position=\"left\" link=\"/about-us-style-1/#actions_demo\" title=\"Book a Tee Time\" icon_type=\"fontawesome\" icon_fontawesome=\"\"][/vc_column][/vc_row][vc_row scheme=\"dark\" row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"1\" css=\".vc_custom_1493984349564{background: #f7f7f7 url(http://triompher.ancorathemes.com/wp-content/uploads/2017/04/pimgpsh_fullsize_distr.jpg?id=618) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}\"][vc_column column_align=\"center\" icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" padding=\"none\"][vc_empty_space alter_height=\"medium\" hide_on_mobile=\"\" css=\".vc_custom_1493984770952{margin-bottom: 1rem !important;}\"][trx_sc_layouts_title title=\"1\" meta=\"\" breadcrumbs=\"1\" icon_type=\"fontawesome\" icon_fontawesome=\"\"][vc_empty_space alter_height=\"medium\" hide_on_mobile=\"\" css=\".vc_custom_1493984775560{margin-bottom: 0.6rem !important;}\"][/trx_sc_content][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1493994341441{padding-top: 1.25em !important;padding-right: 2.3em !important;padding-bottom: 1.25em !important;padding-left: 2.7em !important;}.vc_custom_1493984349564{background: #f7f7f7 url(http://triompher.ancorathemes.com/wp-content/uploads/2017/04/pimgpsh_fullsize_distr.jpg?id=618) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}.vc_custom_1493900457245{margin-top: -7px !important;}.vc_custom_1493984770952{margin-bottom: 1rem !important;}.vc_custom_1493984775560{margin-bottom: 0.6rem !important;}'
						)
				),
		'header_27' => array(
				'name' => 'Header Fullwidth Simple',
				'template' => '<p>[vc_row equal_height=\"yes\" content_placement=\"middle\" row_type=\"compact\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1493995991974{padding-top: 1.25em !important;padding-right: 2.3em !important;padding-bottom: 1.25em !important;padding-left: 2.7em !important;}\" el_class=\"ipad-row\"][vc_column width=\"1/4\" column_align=\"left\" icons_position=\"left\" column_type=\"center\" css=\".vc_custom_1493900457245{margin-top: -7px !important;}\"][trx_sc_layouts_logo][/vc_column][vc_column width=\"1/2\" column_align=\"center\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" hover=\"slide_line\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column][vc_column width=\"1/4\" column_align=\"right\" icons_position=\"left\" offset=\"vc_hidden-md vc_hidden-sm vc_hidden-xs\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"icon-phone-2\" text2=\"0 (800) 123-456\" link=\"tel:0800123456\"][trx_sc_button type=\"default\" size=\"small\" color_style=\"link2\" icon_position=\"left\" link=\"/about-us-style-1/#actions_demo\" title=\"Book a Tee Time\" icon_type=\"fontawesome\" icon_fontawesome=\"\"][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1493995991974{padding-top: 1.25em !important;padding-right: 2.3em !important;padding-bottom: 1.25em !important;padding-left: 2.7em !important;}.vc_custom_1493900457245{margin-top: -7px !important;}'
						)
				),
		'header_34' => array(
				'name' => 'Header Transparent Split menu',
				'template' => '<p>[vc_row equal_height=\"yes\" content_placement=\"middle\" scheme=\"dark\" row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1493995154747{padding-top: 1.35em !important;padding-right: 2.4em !important;padding-bottom: 1.35em !important;padding-left: 3.4em !important;background-color: rgba(0,0,0,0) !important;*background-color: rgb(0,0,0) !important;}\"][vc_column width=\"1/6\" icons_position=\"left\" offset=\"vc_hidden-sm vc_hidden-xs\"][trx_sc_layouts_iconed_text icon=\"icon-untitled-1\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" icon_type=\"fontawesome\" icon_fontawesome=\"icon-clock\" text2=\"0 (800) 123-456\" link=\"tel:0800123456\"][/vc_column][vc_column width=\"1/4\" column_align=\"right\" icons_position=\"left\" column_type=\"center\"][trx_sc_layouts_menu location=\"none\" menu=\"split-left\" hover=\"slide_line\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column][vc_column width=\"1/6\" column_align=\"center\" icons_position=\"left\" css=\".vc_custom_1493903028838{margin-top: -0.6rem !important;}\"][trx_sc_layouts_logo logo=\"684\" logo_retina=\"685\"][trx_sc_layouts_menu type=\"burger\" location=\"none\" menu=\"none\" mobile_button=\"1\" mobile_menu=\"\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column][vc_column width=\"1/4\" column_align=\"left\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"split-right\" hover=\"slide_line\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column][vc_column width=\"1/6\" icons_position=\"left\" offset=\"vc_hidden-sm vc_hidden-xs\"][trx_sc_button type=\"default\" align=\"right\" icon_position=\"left\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" link=\"/about-us-style-1/#actions_demo\" title=\"Book a Tee Time\"][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1493995154747{padding-top: 1.35em !important;padding-right: 2.4em !important;padding-bottom: 1.35em !important;padding-left: 3.4em !important;background-color: rgba(0,0,0,0) !important;*background-color: rgb(0,0,0) !important;}.vc_custom_1493903028838{margin-top: -0.6rem !important;}'
						)
				)
		);
?>